const {chromium}=require('playwright');const fs=require('fs');const crypto=require('crypto');const path=require('path');const assert=require('assert/strict');
(async()=>{const root=path.resolve(__dirname,'..'),checks=[],errors=[],requests=[];const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const page=await browser.newPage({viewport:{width:1360,height:1050}});page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>requests.push(r.url()));
 const check=(name,value,detail)=>{checks.push({name,passed:!!value,detail});assert(value,name)};
 await page.goto('http://127.0.0.1:4173/');await page.waitForSelector('.word');await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:path.join(root,'evidence/desktop.png'),fullPage:true});
 check('114 directory links',await page.locator('.surah-link').count()===114);
 check('No PDF/image/canvas content',await page.locator('#content img,#content svg,#content canvas,#content iframe,#content object,#content embed').count()===0);
 check('Only current page fetched',requests.filter(x=>/\/data\/pages\//.test(x)).length===1);
 const source=JSON.parse(fs.readFileSync(path.join(root,'dist/data/pages/001.json'))).originalCandidate;const expected=source.rows.flatMap(r=>r.arabic_segments.flatMap(s=>s.words.map(w=>w.text)));
 check('All page 1 word codepoints preserved',JSON.stringify(await page.locator('.word').allTextContents())===JSON.stringify(expected));
 check('Visible text can be selected',await page.locator('.word').first().evaluate(e=>{const r=document.createRange();r.selectNodeContents(e);const s=getSelection();s.removeAllRanges();s.addRange(r);const equal=s.toString()===e.textContent;s.removeAllRanges();return equal}));
 for(const width of [1360,390,320]){await page.setViewportSize({width,height:900});for(const size of [26,34,56]){await page.locator('#font-size').fill(String(size));await page.locator('#font-size').dispatchEvent('input');check(`No horizontal overflow ${width}/${size}`,await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));}}
 await page.setViewportSize({width:390,height:844});await page.locator('#font-size').fill('34');await page.locator('#font-size').dispatchEvent('input');await page.locator('#font-size').blur();await page.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));await page.screenshot({path:path.join(root,'evidence/mobile.png'),fullPage:false});
 await page.goto('http://127.0.0.1:4173/#surah=2&page=3');await page.waitForSelector('[data-word-id="r10w1"]');await page.screenshot({path:path.join(root,'evidence/complex-page-003-mobile.png'),fullPage:true});
 await page.selectOption('#ayah-select','2:8');await page.waitForSelector('.highlight');check('Ayah navigation highlights source row',await page.locator('.highlight [data-ayah="2:8"]').count()>0);
 await page.goto('http://127.0.0.1:4173/#surah=2&page=6');await page.waitForSelector('[data-word-id="r2w1"]');check('Cross-page ayah directory',await page.locator('#ayah-select option[value=\"2:5\"]').count()===1);
 check('Partial page visibly identified',(await page.locator('.page-issues').innerText()).includes('মাত্র ৩টি সারি'));
 await page.goto('http://127.0.0.1:4173/#surah=114');await page.waitForFunction(()=>document.querySelector('#surah-title').textContent==='আন-নাস');check('Missing surah never substituted',await page.locator('.word').count()===0&&(await page.locator('#content').innerText()).includes('প্রস্তুত হয়নি'));
 await page.locator('#list-toggle').click();check('Mobile directory opens',await page.locator('#sidebar').isVisible());await page.locator('#search').fill('ফাতিহা');check('Directory search',await page.locator('.surah-link').count()===1);await page.locator('.surah-link').click();await page.waitForSelector('.word');check('Mobile directory closes on selection',!(await page.locator('#sidebar').isVisible()));
 await page.locator('#progress-open').click();check('All surahs have persistent progress',await page.locator('#progress-content tr').count()===115);check('Zero completed claims',(await page.locator('.stats').innerText()).includes('০/১১৪'));await page.locator('#progress-close').click();
 // Synthetic mechanics only: deliberately unrelated to source transcription.
 const fixture=await page.evaluate(async()=>{const {placeVerifiedAnchor}=await import('./anchors.js');const wrap=document.createElement('span');wrap.style.cssText='position:relative;display:inline-block;font:34px Quran';const body=document.createElement('span');body.textContent='بَتَ';const mark=document.createElement('span');mark.style.position='absolute';mark.textContent='১';wrap.append(body,mark);document.body.append(wrap);const g={id:'SYNTHETIC:g0',text:'بَ',startCodepoint:0,endCodepoint:2,sourceBox:[0,0,1,1],verified:true};let rejected=false;try{placeVerifiedAnchor(wrap,body,mark,{verified:false},[g])}catch{rejected=true}placeVerifiedAnchor(wrap,body,mark,{verified:true,targetGraphemeId:g.id},[g]);const ok=mark.dataset.targetGrapheme===g.id&&Number.isFinite(parseFloat(mark.style.left));wrap.remove();return {rejected,ok}});check('Unverified anchor refused',fixture.rejected);check('Synthetic Range anchor mechanism only',fixture.ok);
 check('No runtime errors',!errors.length,errors);check('No remote content requests',requests.every(u=>u.startsWith('http://127.0.0.1:4173/')),requests.filter(u=>!u.startsWith('http://127.0.0.1:4173/')));
 await browser.close();fs.writeFileSync(path.join(root,'evidence/browser-check.json'),JSON.stringify({status:'pass',assetHashes:Object.fromEntries(['index.html','app.js','anchors.js','style.css','fonts/Amiri-Regular.woff2','fonts/NotoSansBengali-VF.woff2','data/manifest.json'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'dist',p))).digest('hex')])),scope:'UI mechanics only, not source transcription, exact glyph appearance or verified letter position',checks,errors},null,2));console.log(JSON.stringify({passed:checks.length,errors}));})().catch(e=>{console.error(e);process.exitCode=1});
