const {chromium}=require('playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
(async()=>{const root=path.resolve(__dirname,'..'),out=path.join(root,'evidence/fatiha-opening-2026-10-03');const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const p=await browser.newPage(),checks=[],errors=[];p.on('pageerror',e=>errors.push(e.message));function check(name,value){checks.push({name,passed:!!value});assert(value,name)}
await p.goto('http://127.0.0.1:4173/#surah=1');await p.waitForSelector('.source-opening-word');await p.evaluate(()=>document.fonts.ready);
const source=JSON.parse(fs.readFileSync(path.join(root,'dist/data/pages/001.json'))).originalCandidate;
check('Source header precedes unnumbered basmala',await p.evaluate(()=>!!(document.querySelector('.source-opening').compareDocumentPosition(document.querySelector('.basmala'))&Node.DOCUMENT_POSITION_FOLLOWING)));
check('Source header transcription retained',await p.locator('.source-opening h2').textContent()===source.surah_header.bengali);
check('Four scoped source words',await p.locator('.source-opening-word').count()===4);
check('Five scoped source annotations',await p.locator('.source-opening-word .opening-mark').count()===5);
check('Original Arabic codepoints unchanged',JSON.stringify(await p.locator('.word').allTextContents())===JSON.stringify(source.rows.flatMap(r=>r.arabic_segments.flatMap(s=>s.words.map(w=>w.text)))));
check('Actual text selectable',await p.locator('.source-opening-word .word').evaluateAll(es=>es.every(e=>{const r=document.createRange();r.selectNodeContents(e);const s=getSelection();s.removeAllRanges();s.addRange(r);const ok=s.toString()===e.textContent;s.removeAllRanges();return ok})));
check('No image, SVG, canvas, or hidden substitute',await p.locator('#content img,#content svg,#content canvas,#content object,#content iframe').count()===0);
for(const width of [1360,390,320])for(const size of [26,34,56]){await p.setViewportSize({width,height:950});await p.locator('#font-size').fill(String(size));await p.locator('#font-size').dispatchEvent('input');await p.evaluate(()=>new Promise(r=>requestAnimationFrame(()=>requestAnimationFrame(r))));check(`No horizontal overflow ${width}/${size}`,await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));check(`Verse ending stays with final word ${width}/${size}`,await p.locator('.opening-tail').evaluate(e=>{const w=e.querySelector('.word-wrap').getBoundingClientRect(),m=e.querySelector('.opening-ending').getBoundingClientRect();return Math.abs(w.top-m.top)<1&&m.right<=w.left+1}));check(`Five visible upper signs ${width}/${size}`,await p.locator('.opening-mark').evaluateAll(es=>es.length===5&&es.every(e=>getComputedStyle(e).visibility==='visible'&&e.getBoundingClientRect().width>0)));check(`Source glyph position scales with word ${width}/${size}`,await p.locator('.source-opening-word .opening-mark').evaluateAll(es=>es.every(e=>{const b=e.getBoundingClientRect(),w=e.parentElement.getBoundingClientRect(),f=parseFloat(getComputedStyle(e.parentElement).fontSize);return Math.abs((b.left-w.left)/f-Number(e.dataset.sourceLeftEm))<.025})));}
await p.setViewportSize({width:1360,height:950});await p.locator('#font-size').fill('34');await p.locator('#font-size').dispatchEvent('input');await p.locator('.text-row').first().scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'after-desktop.png')});await p.setViewportSize({width:390,height:900});await p.locator('.text-row').first().scrollIntoViewIfNeeded();await p.screenshot({path:path.join(out,'after-mobile.png')});await p.locator('#show-marks').uncheck();check('Hide marks removes only instructional signs',await p.locator('.opening-mark').count()===0&&await p.locator('.source-opening-word').count()===4);await p.goto('http://127.0.0.1:4173/#surah=2');await p.waitForSelector('.word');check('No scoped font applied to other source occurrences',await p.locator('.source-opening-word').count()===0);check('No runtime errors',!errors.length);await browser.close();const files=['app.js','opening.js','style.css','data/opening-typography.json','fonts/FatihahOpening.woff2'];fs.writeFileSync(path.join(out,'browser-check.json'),JSON.stringify({status:'pass',scope:'Four-word first-ayah native font and relative geometry mechanics, not whole-page fidelity or verified letter identities',checks,errors,hashes:Object.fromEntries(files.map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,'dist',f))).digest('hex')]))},null,2));console.log(JSON.stringify({passed:checks.length,errors}));})().catch(e=>{console.error(e);process.exitCode=1});
