import {placeVerifiedAnchor} from './anchors.js';
const $=id=>document.getElementById(id), bn=n=>String(n).replace(/\d/g,d=>'০১২৩৪৫৬৭৮৯'[d]);
const el=(tag,cls,text)=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text!==undefined)n.textContent=text;return n};
const cache=new Map();let manifest,surah=1,pageNo=1,requestId=0,activeDoc;
const anchorUpdates=[];
async function json(url){const r=await fetch(url);if(!r.ok)throw new Error(`ডেটা লোড হয়নি (${r.status})`);return r.json()}
function route(){const p=new URLSearchParams(location.hash.slice(1));return {surah:Number(p.get('surah'))||1,page:Number(p.get('page'))||null,ayah:p.get('ayah')}}
function navigate(sid,p=null,a=null){const q=new URLSearchParams({surah:sid});if(p)q.set('page',p);if(a)q.set('ayah',a);const h='#'+q;if(location.hash===h)loadRoute();else location.hash=h}
function directory(){const q=$('search').value.trim().toLowerCase().replace(/[০-৯]/g,d=>'০১২৩৪৫৬৭৮৯'.indexOf(d));$('surah-list').replaceChildren();let count=0;for(const s of manifest.surahs){if(q&&!`${s.id} ${s.nameBn} ${s.nameAr}`.toLowerCase().includes(q))continue;count++;const a=el('a','surah-link'+(s.pages.length?' has-draft':''));a.href='#surah='+s.id;if(s.id===surah)a.setAttribute('aria-current','page');a.append(el('span','num',bn(s.id)));const label=el('span');label.append(el('strong','',s.nameBn),el('small','',s.pages.length?'আংশিক খসড়া আছে':'পাঠ রূপান্তর বাকি'));a.append(label,el('span','state-dot'));a.onclick=()=>{$('sidebar').classList.remove('open');$('list-toggle').setAttribute('aria-expanded','false')};$('surah-list').append(a)}if(!count)$('surah-list').append(el('p','empty','এই নামে কোনো সূরা পাওয়া যায়নি।'))}
function option(value,label){const o=el('option','',label);o.value=value;return o}
function controls(s,doc){$('page-select').replaceChildren();for(const p of s.pages)$('page-select').append(option(p,bn(p)+(p===6?' · আংশিক':'')));$('page-select').value=String(pageNo);$('page-select').disabled=!s.pages.length;
 $('ayah-select').replaceChildren(option('','নির্বাচন করুন'));for(const a of s.draftAyahs)$('ayah-select').append(option(a,bn(a.split(':')[1])));$('ayah-select').disabled=!doc;
 const pos=s.pages.indexOf(pageNo);$('previous').disabled=pos<=0;$('next').disabled=pos<0||pos>=s.pages.length-1;$('page-count').textContent=s.pages.length?`${bn(pos+1)} / ${bn(s.pages.length)} সংরক্ষিত পৃষ্ঠা`:'';
 $('page-label').textContent=doc?`মূল PDF · পৃষ্ঠা ${bn(pageNo)}${doc.originalCandidate.printed_page?' · মুদ্রিত '+doc.originalCandidate.printed_page:''}`:'এই সূরার পাঠ এখনো রূপান্তর হয়নি';$('reader').dataset.page=pageNo;
}
function renderWord(word,marks,doc){const wrap=el('span','word-wrap'+(!$('show-marks').checked?' no-marks':''));wrap.dataset.wordId=word.id;const body=el('span','word',word.text);body.lang='ar';body.dir='rtl';wrap.append(body);
 if($('show-marks').checked)for(const m of marks){const a=doc.annotations.find(a=>a.sourceId===m.id),n=el('span','mark'+(!m.printed?' unknown':''),m.printed||'?');n.dir='ltr';n.lang='bn';n.dataset.annotation=m.id;n.dataset.enclosure=m.enclosure||'none';n.title=`${m.legend_bengali||m.shape_description||'অমীমাংসিত চিহ্ন'} — অক্ষরভিত্তিক অবস্থান যাচাই হয়নি`;const fraction=m.attachment?.offset_in_word;if(Number.isFinite(fraction))n.style.right=`${fraction*100}%`;else {n.style.right='50%';n.classList.add('unknown')}
  if(a?.verified&&a.targetGraphemeId){anchorUpdates.push(()=>placeVerifiedAnchor(wrap,body,n,a,doc.graphemes[word.id]));}wrap.append(n)}return wrap}
function render(doc){activeDoc=doc;anchorUpdates.length=0;const container=$('content');container.replaceChildren();const d=doc.originalCandidate;
 if(d.basmala){const b=el('section','basmala');const ar=el('div','ar',d.basmala.arabic);ar.lang='ar';ar.dir='rtl';b.append(ar,el('p','bn',d.basmala.bengali));container.append(b)}
 for(const row of d.rows){const block=el('section','text-row');block.dataset.row=row.row_index;block.append(el('div','row-title',`মূলের সারি ${bn(row.row_index+1)}`));const flow=el('div','arabic-flow');flow.lang='ar';flow.dir='rtl';const marks=(row.annotation_band||{}).glyphs||[];
  for(const seg of row.arabic_segments){for(let i=0;i<(seg.words||[]).length;i++){const w=seg.words[i],word=renderWord(w,marks.filter(m=>m.attachment?.target===w.id),doc);word.dataset.ayah=seg.ayah_ref;if(i===0&&!container.querySelector(`[data-ayah-start="${seg.ayah_ref}"]`))word.dataset.ayahStart=seg.ayah_ref;flow.append(word,document.createTextNode(' '))}
   if(seg.stop_sign||seg.verse_marker){const end=el('span','verse-end');if(seg.stop_sign?.printed)end.append(el('span','stop',seg.stop_sign.printed));if(seg.verse_marker?.numeral_bn)end.append(el('span','verse-number',seg.verse_marker.numeral_bn));flow.append(end)}
  }block.append(flow);
  for(const seg of row.bengali_segments||[]){const p=el('p','translation');p.append(el('span','ref',seg.numeral_bn||bn(seg.ayah_ref?.split(':')[1]||'')),document.createTextNode(seg.text));block.append(p)}
  if(marks.length){const details=el('details','row-evidence');details.append(el('summary','',`${bn(marks.length)}টি চিহ্নের তথ্য · সবগুলোর অক্ষর-সংযোগ যাচাই বাকি`));const list=el('ul');for(const m of marks){list.append(el('li','',`${m.printed||'[পাঠ/আকৃতি অমীমাংসিত]'} · ${m.legend_bengali||m.shape_description||'অমীমাংসিত'} · উৎসের লক্ষ্য: ${m.attachment?.target||'অজানা'}${!m.printed?' · ওপরের ? কেবল অমীমাংসিত অংশের সংকেত':''}`))}details.append(list);const wordIds=new Set(row.arabic_segments.flatMap(s=>s.words.map(w=>w.id)));const unplaced=marks.filter(m=>!wordIds.has(m.attachment?.target));if(unplaced.length){details.open=true;block.append(el('p','unplaced-note',`${bn(unplaced.length)}টি চিহ্নের শব্দের ওপর অবস্থান দেখানো যায়নি; নিচে অমীমাংসিত হিসেবে সংরক্ষিত আছে।`))}block.append(details)}container.append(block)
 }
 const issues=(d.unresolved||[]).filter(u=>u.status!=='resolved');const box=el('section','page-issues');box.append(el('h3','',pageNo===6?'পৃষ্ঠা ৬-এর মাত্র ৩টি সারি সংরক্ষিত; বাকি অংশ অনুপস্থিত।':'এই পৃষ্ঠার পূর্ণ যাচাই শেষ হয়নি।'));const list=el('ul');list.append(el('li','','কারিয়ানা চিহ্নগুলো এখনো নির্দিষ্ট অক্ষরের সঙ্গে যাচাইকৃতভাবে যুক্ত নয়।'),el('li','','ফন্টের অক্ষর, হরকত ও চিহ্নের জ্যামিতি মূলের হুবহু হিসেবে অনুমোদিত নয়।'));for(const u of issues)list.append(el('li','',u.question||u.description||u.id));box.append(list);container.append(box);
 renderFurniture(d,container);scheduleAnchors();}
let anchorFrame;function scheduleAnchors(){cancelAnimationFrame(anchorFrame);anchorFrame=requestAnimationFrame(()=>{for(const fn of anchorUpdates)try{fn()}catch(err){console.warn('Anchor withheld:',err.message)};withholdCollisions()})}
function withholdCollisions(){
 for(const row of document.querySelectorAll('.text-row')){
  const marks=[...row.querySelectorAll('.mark')];marks.forEach(m=>{m.style.visibility='visible';delete m.dataset.withheld});const blocked=new Set();
  for(let i=0;i<marks.length;i++){const a=marks[i].getBoundingClientRect();for(let j=i+1;j<marks.length;j++){const b=marks[j].getBoundingClientRect();if(a.left<b.right&&a.right>b.left&&a.top<b.bottom&&a.bottom>b.top){blocked.add(marks[i]);blocked.add(marks[j])}}}
  blocked.forEach(m=>{m.style.visibility='hidden';m.dataset.withheld='collision'});
  let note=row.querySelector('.collision-note');if(blocked.size){if(!note){note=el('p','collision-note');row.querySelector('.row-evidence').before(note)}note.textContent=`${bn(blocked.size)}টি চিহ্ন কাছাকাছি পড়ে অস্পষ্ট হচ্ছিল। অনুমান করে স্থান বদলানো হয়নি; নিচের তালিকায় পাঠ ও তথ্য দেখুন।`;note.hidden=false;row.querySelector('.row-evidence').open=true}else if(note)note.hidden=true;
 }
}
function renderFurniture(d,container){
 const items=d.page_furniture||[],header=d.surah_header;if(!items.length&&!header)return;
 const section=el('section','source-furniture');section.append(el('h3','','মূলের শিরোনাম ও প্রান্তলেখা · খসড়া'),el('p','furniture-note','সংরক্ষিত পাঠ নিচে আছে। অলংকৃত অক্ষর, চিহ্ন ও মূলের বিন্যাসের চূড়ান্ত যাচাই বাকি।'));
 if(header){const ar=el('p','header-ar',header.arabic);ar.lang='ar';ar.dir='rtl';section.append(ar);for(const k of ['bengali','surah_number_bn','revelation_bn','ruku_bn','ayah_count_bn'])if(header[k]){const labels={bengali:'শিরোনাম',surah_number_bn:'সূরা',revelation_bn:'অবতরণ',ruku_bn:'রুকু',ayah_count_bn:'আয়াত'};section.append(el('p','',labels[k]+': '+header[k]))}}
 for(const item of items){if(item.symbol){const symbol=el('p','furniture-symbol',item.symbol);symbol.lang='ar';symbol.dir='rtl';section.append(symbol)}if(item.observed_components_top_to_bottom){const components=el('p','furniture-components','নথিভুক্ত ওপর থেকে নিচের অংশ: ');const shapes={'vertical stroke':'[উল্লম্ব রেখা: আকৃতির বর্ণনা]','horizontal rule':'[অনুভূমিক রেখা: আকৃতির বর্ণনা]'};components.append(document.createTextNode(item.observed_components_top_to_bottom.map(t=>shapes[t]||t).join(' · ')));section.append(components)}if(item.text){const p=el('p','furniture-text',item.text);if(item.language==='ar'){p.lang='ar';p.dir='rtl'}section.append(p)}else if(item.kind!=='footer_legend'){section.append(el('p','furniture-unresolved','প্রান্তলেখার পাঠ অমীমাংসিত। সম্ভাব্য পাঠকে নিশ্চিত পাঠ হিসেবে দেখানো হয়নি।'))}
  if(item.entries){const list=el('ul');for(const e of item.entries)list.append(el('li','',(e.printed||'[চিহ্নের পাঠ অমীমাংসিত]')+' — '+e.text));section.append(list)}
 }
 container.append(section);
}
async function loadRoute(){const req=++requestId,r=route();surah=Number.isInteger(r.surah)&&r.surah>=1&&r.surah<=114?r.surah:1;const s=manifest.surahs[surah-1];pageNo=s.pages.includes(r.page)?r.page:(s.pages[0]||0);directory();$('current-name').textContent=s.nameBn;$('surah-number').textContent='সূরা '+bn(surah);$('surah-title').textContent=s.nameBn;$('surah-arabic').textContent=s.nameAr;$('surah-caption').textContent=s.pages.length?`${bn(s.pages.length)}টি উৎস-পৃষ্ঠায় সংরক্ষিত খসড়া · সম্পূর্ণ সূরা যাচাই হয়নি`:'মূল PDF থেকে এই সূরার পাঠ রূপান্তর বাকি';activeDoc=null;controls(s,null);
 if(!s.pages.length){$('content').replaceChildren();const b=el('div','empty');b.append(el('strong','','এই সূরার পাঠ এখনো প্রস্তুত হয়নি।'),document.createTextNode('মূল PDF থেকে আরবি, বাংলা ও সব চিহ্ন উদ্ধার ও যাচাই বাকি। এখানে অনুমান বা অন্য সংস্করণের পাঠ বসানো হয়নি।'));$('content').append(b);return}
 $('content').replaceChildren(el('p','empty','সংরক্ষিত পাঠ লোড হচ্ছে…'));try{const file=manifest.pages[pageNo-1].file;let doc=cache.get(pageNo);if(!doc){doc=await json(file);cache.set(pageNo,doc);if(cache.size>3)cache.delete(cache.keys().next().value)}if(req!==requestId)return;render(doc);controls(s,doc);if(r.ayah)jumpAyah(r.ayah)}catch(err){if(req===requestId){$('content').replaceChildren(el('p','empty error',err.message),Object.assign(el('button','','আবার চেষ্টা করুন'),{onclick:loadRoute}));}}}
function jumpAyah(ref){const target=[...document.querySelectorAll('[data-ayah]')].find(e=>e.dataset.ayah===ref);document.querySelectorAll('.highlight').forEach(n=>n.classList.remove('highlight'));if(target){target.closest('.text-row').classList.add('highlight');target.scrollIntoView({block:'center',behavior:'instant'});$('ayah-select').value=ref}}
function progress(){const root=$('progress-content');root.replaceChildren();const s=manifest.summary,stats=el('div','stats');for(const [value,label]of [[s.verifiedSurahs+'/114','সম্পূর্ণ যাচাইকৃত সূরা'],[s.fullyVerifiedPages+'/760','সম্পূর্ণ যাচাইকৃত পৃষ্ঠা'],[s.verifiedLetterAnchors+'/'+s.annotations,'যাচাইকৃত অক্ষর-সংযোগ']]){const stat=el('div','stat');stat.append(el('strong','',bn(value)),document.createTextNode(label));stats.append(stat)}root.append(stats,el('p','',`৭টি পৃষ্ঠায় ৫৭টি সারি ও ৪৯৭টি শব্দের খসড়া আছে। পৃষ্ঠা ৬ অসম্পূর্ণ; আরও ৭৫৩টি পৃষ্ঠার প্রতিলিপি নেই। ৭৬০টি পৃষ্ঠার টেক্সট স্তর পরীক্ষা করা হয়েছে—আরবি বা বাংলা পাঠ পাওয়া যায়নি।`));const ul=el('ul');for(const t of ['পৃষ্ঠা ১–২-এর মূল পাঠের পুরোনো স্বাধীন পর্যালোচনা আছে; সেটি এই ওয়েবের ফন্ট বা অক্ষর-সংযোগের অনুমোদন নয়।','পৃষ্ঠা ৩-এর একটি ক্ষতিগ্রস্ত চিহ্ন এবং অলংকৃত শিরোনামসহ অমীমাংসিত অংশ রয়েছে।','পৃষ্ঠা ৪–৭-এর খসড়া ও বইয়ের সম্পূর্ণ ধারাবাহিকতা যাচাই বাকি।','৭৬০টি PDF পৃষ্ঠা মানেই ৭৬০টি স্বতন্ত্র কুরআনের পৃষ্ঠা নয়: পুনরাবৃত্ত স্ক্যান ও পরিশিষ্ট আছে।'])ul.append(el('li','',t));root.append(ul);const scroll=el('div','progress-table'),table=el('table');const head=el('tr');for(const t of ['সূরা','খসড়া আয়াতের উল্লেখ','পূর্ণ যাচাই'])head.append(el('th','',t));table.append(head);for(const sur of manifest.surahs){const tr=el('tr');tr.append(el('td','',`${bn(sur.id)}. ${sur.nameBn}`),el('td','',sur.draftAyahs.length?`${bn(sur.draftAyahs.length)} · আংশিক`:'নেই'),el('td','','বাকি'));table.append(tr)}scroll.append(table);root.append(scroll,el('p','','সূরার তালিকা নেভিগেশন মেটাডেটা; তালিকার নাম PDF-এর শিরোনাম থেকে হুবহু যাচাই করা হয়নি।'));const hash=el('p','','মূল PDF SHA-256: ');hash.append(el('code','',manifest.source.sha256));root.append(hash);$('progress-dialog').showModal()}
$('search').addEventListener('input',()=>manifest&&directory());$('list-toggle').onclick=()=>{const on=$('sidebar').classList.toggle('open');$('list-toggle').setAttribute('aria-expanded',on)};$('progress-open').onclick=()=>manifest&&progress();$('details-open').onclick=()=>manifest&&progress();$('progress-close').onclick=()=>$('progress-dialog').close();$('progress-dialog').onclick=e=>{if(e.target===$('progress-dialog')&&e.offsetX<0)$('progress-dialog').close()};
$('page-select').onchange=e=>navigate(surah,Number(e.target.value));$('ayah-select').onchange=e=>{if(e.target.value){const a=e.target.value;const target=manifest.pages[pageNo-1]?.ayahs.includes(a)?pageNo:manifest.pages.find(p=>p.ayahs.includes(a))?.page;navigate(surah,target,a)}};$('previous').onclick=()=>{const p=manifest.surahs[surah-1].pages;navigate(surah,p[p.indexOf(pageNo)-1])};$('next').onclick=()=>{const p=manifest.surahs[surah-1].pages;navigate(surah,p[p.indexOf(pageNo)+1])};
function font(value){value=Math.max(26,Math.min(56,Number(value)||34));document.documentElement.style.setProperty('--arabic-size',value+'px');$('font-size').value=value;$('font-value').value=bn(value);scheduleAnchors();try{localStorage.setItem('quran-font-size',value)}catch{}}
$('font-size').oninput=e=>font(e.target.value);$('show-marks').onchange=()=>{if(activeDoc)render(activeDoc);$('anchor-note').hidden=!$('show-marks').checked};window.addEventListener('hashchange',()=>manifest&&loadRoute());new ResizeObserver(scheduleAnchors).observe($('content'));document.fonts.addEventListener('loadingdone',scheduleAnchors);try{font(localStorage.getItem('quran-font-size')||34)}catch{font(34)}
try{manifest=await json('data/manifest.json');await loadRoute()}catch(err){$('content').replaceChildren(el('p','empty error','ডেটা লোড করা যায়নি। পৃষ্ঠাটি আবার লোড করুন।'));console.error(err)}
